### ISSUE TITLE
TypeError: iteration over a 0-d array

### ISSUE THREAD

**Issue by AtmaHou** [devalab/CIGIN#8]
Hi, I conduct experiments on MNSol, and get the following error in the collate function. 
(I am running: python main.py --name cigin --interaction dot --batch_size 32)

```
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    main()
  File "main.py", line 104, in main
    train(max_epochs, model, optimizer, scheduler, train_loader, valid_loader, project_name)
  File "/users7/ythou/Projects/code/Medical/CIGIN/CIGIN_V2/train.py", line 40, in train
    for samples in tq_loader:
  File "/users4/ythou/anaconda3/envs/py37/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1032, in __iter__
    for obj in iterable:
  File "/users4/ythou/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/users4/ythou/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "main.py", line 57, in collate
    solute_len_matrix = get_len_matrix(solute_graphs.batch_num_nodes)
  File "/users7/ythou/Projects/code/Medical/CIGIN/CIGIN_V2/utils.py", line 23, in get_len_matrix
    for l in len_list:
TypeError: iteration over a 0-d array
```

Here are the printed results for `solute_graphs.batch_num_nodes`
```
<bound method DGLHeteroGraph.batch_num_nodes of Graph(num_nodes=161, num_edges=270,
      ndata_schemes={'x': Scheme(shape=(42,), dtype=torch.int64)}
      edata_schemes={'w': Scheme(shape=(10,), dtype=torch.bool)})>
```

How can I deal with it?

**Comment by AtmaHou** [comment]
Solve it!

Solution:
.batch_num_nodes   ——> .batch_num_nodes()
